/**
 * Even Fibonacci numbers
 *
 * Problem 2
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 *
 * Brainstorming:
 * I think I will maybe need to use recursion? I might use 4 million as the
 * parameter and use a recursive method top go through each value and add them
 * up. I will also need to only add the sum of the even numbers. I'm trying to
 * use as little resources as I can, but I did search up the fibonacci formula.
 * I'm having issues conceptualizing the fib formula.
 *
 * Results:
 * First Compile Didn't work, created a stackOverFlow
 * I think I figured it out. Definitely was not optimal but I added 3 parameters
 * an input, previous input and sum.
 * Answer: 4613732
 * And I got it! The problem worked out
 * I rated this a 4/10 just because I don't have the fibonacci method memorized.
 * Other than that it was fairly easy, took about 20 minutes.
 * First Submit too.
 */
public class Problem2 {

    /**
     * starts program and executes the generator. Prints out the solution.s
     * @param args arguments to be passed in.
     */
    public static void main(String[] args) {
        System.out.println(fibonacciGenerator(0, 0,0));
    }


    /**
     * This method uses recursion to solve the problem.
     *
     * Uses three base cases: if input is larger than 4 million, if input is 0,
     * and if input is 1.
     * Otherwise uses the standard fibonacci formula. Note that I used sum = at
     * each recursive call. If not it would always return 0.
     * @param input current fibonacci number
     * @param previousInput last fibonacci number
     * @param sum total sum of all numbers.
     * @return a value representing the sum.
     */
    private static int fibonacciGenerator(int input,int previousInput, int sum) {
        if (input > 4000000) {
            return sum;
        }

        if (input == 0) {
            sum = fibonacciGenerator(1, 0,sum);
        } else if (input == 1) {

            sum = fibonacciGenerator(1+ previousInput,1,sum);
        } else {
            if (input % 2 == 0) {
                sum += input;

            }
            sum = fibonacciGenerator(input+previousInput,input,sum);

        }



        return sum;
    }
}
